name: Test

on:
  push:
    branches: [ master ]
    paths: ['**.js']

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Install
        run: |
          npm install

      - name: Run test
        run: |
          npm run test

      - name: Run test coverage
        run: |
          npm run test:coverage

      - name: Codecov
        uses: codecov/codecov-action@v1
        with:
          token: 31ff9634-b8a6-4ee3-a53f-3c54c3de4db9
